version: '3'

services:
  compute:
    build:
      context: ./compute
      dockerfile: Dockerfile
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: vectors
      REDIS_ADDR: redis:6379
      VECTOR_DIMENSION: "128"
      SERVER_ADDR: ":3000"
    ports:
      - "3000:3000"
    depends_on:
      - minio
      - redis

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
