version: '2'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_HOST: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      VECTOR_DIM: 128
    depends_on:
      - redis
      - minio

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: sh
    command: -c 'mkdir -p /data && minio server /data --console-address ":9001"'
